# -*- coding: utf-8 -*-
"""analyzing_data_with_python.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xuo0SmlLqw8qiViQ-JOuhl6leM-y7jNC
"""

# Load CSV to SQLite3 with Pandas

import pandas as pd
import sqlite3

data = pd.read_csv('./menu.csv')

conn = sqlite3.connect('McDonalds.db')

data.to_sql("MCDONALDS_NUTRITION", conn)

df = pd.read_sql("SELECT * FROM MCDONALDS_NUTRITION", conn)
df.head()

df.describe(include='all')

"""## Visualização"""

# Commented out IPython magic to ensure Python compatibility.
import matplotlib.pyplot as plt
# %matplotlib inline
import seaborn as sns

plot = sns.swarmplot(x='Category', y='Sodium', data=df)
plt.setp(plot.get_xticklabels(), rotation=70)
plt.title('Sodium Content')
plt.show()

df['Sodium'].describe()

df['Sodium'].idxmax()

df.at[82, 'Item']

plot = sns.jointplot(x='Protein', y='Total Fat', data=df)

plot = sns.set_style('whitegrid')
ax = sns.boxplot(x=df['Sugars'])