# -*- coding: utf-8 -*-
"""hands_on_lab_03.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qXgiaROhLoU5vUi105RZwWAVYi5QYhqb
"""

# Commented out IPython magic to ensure Python compatibility.
import seaborn as sns
# %load_ext sql

import csv, sqlite3

con = sqlite3.connect("socioeconomic.db")
cur = con.cursor()

# Commented out IPython magic to ensure Python compatibility.
# %sql sqlite:///socioeconomic.db

import pandas

df = pandas.read_csv('https://data.cityofchicago.org/resource/jcxq-k9xf.csv')
df.to_sql("chicago_socioeconomic_data", con, if_exists='replace', index=False,method="multi")

# Install the 'ipython-sql' and 'prettytable' libraries using pip
!pip install ipython-sql prettytable

# Import the 'prettytable' library, which is used to display data in a formatted table
import prettytable

# Set the default display format for prettytable to 'DEFAULT' (i.e., a simple table format)
prettytable.DEFAULT = 'DEFAULT'

# Commented out IPython magic to ensure Python compatibility.
# %sql SELECT * FROM chicago_socioeconomic_data limit 5;

"""### Problem 1
How many rows are in the dataset?
"""

df.shape

# Commented out IPython magic to ensure Python compatibility.
# %sql SELECT COUNT(*) FROM chicago_socioeconomic_data;

"""### Problem 2
How many community areas in Chicago have a hardship index greater than 50.0?
"""

# Commented out IPython magic to ensure Python compatibility.
# %%sql
# 
# SELECT COUNT(community_area_name) FROM chicago_socioeconomic_data
# WHERE hardship_index > 50;

"""### Problem 3
What is the maximum value of hardship index in this dataset?
"""

# Commented out IPython magic to ensure Python compatibility.
# %%sql
# 
# SELECT MAX(hardship_index) FROM chicago_socioeconomic_data;

"""### Problem 4
Which community area which has the highest hardship index?
"""

# Commented out IPython magic to ensure Python compatibility.
# %%sql
# 
# SELECT community_area_name FROM chicago_socioeconomic_data
# WHERE hardship_index = (SELECT MAX(hardship_index) FROM chicago_socioeconomic_data);

"""### Problem 5
Which Chicago community areas have per-capita incomes greater than $60,000?
"""

# Commented out IPython magic to ensure Python compatibility.
# %%sql
# 
# SELECT community_area_name FROM chicago_socioeconomic_data
# WHERE per_capita_income_ > 60000;

"""### Problem 6
Create a scatter plot using the variables `per_capita_income_` and `hardship_index`. Explain the correlation between the two variables.
"""

# Commented out IPython magic to ensure Python compatibility.
import matplotlib.pyplot as plt
# %matplotlib inline

plt.figure(figsize=(10, 6))
plot = plt.scatter(x='per_capita_income_', y='hardship_index', data=df)
plt.title('Per Capita Income X Hardship Index')
plt.xlabel('Per Capita Income')
plt.ylabel('Hardship Index')
plt.tight_layout()
plt.show()

"""The hardship index rises as the per capita income decreases. This indicates a negative correlation between the two variables. This is because the hardship index is a score that measures community-level economic stress, with higher values indicating greater hardship. This index directly reflects economic conditions, where a decrease in per capita income is strongly correlated with a rise in the Hardship Index."""

df.corr(numeric_only=True)

# -0.849167