# -*- coding: utf-8 -*-
"""hands_on_lab_04.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1l0QIeSjddFLTzOUvlQ6Bw0cGXQ582lVb
"""

import csv, sqlite3

con = sqlite3.connect("RealWorldData.db")
cur = con.cursor()

import prettytable
prettytable.DEFAULT = 'DEFAULT'

# Commented out IPython magic to ensure Python compatibility.
# %load_ext sql

# Commented out IPython magic to ensure Python compatibility.
# %sql sqlite:///RealWorldData.db

"""## Store the dataset in a Table"""

import pandas as pd
import sqlite3

df = pd.read_csv("/content/ChicagoPublicSchools.csv")
df.to_sql("CHICAGO_PUBLIC_SCHOOLS", con, if_exists='replace', index=False,method="multi")

"""### Query the database system catalog to retrieve table metadata"""

# Commented out IPython magic to ensure Python compatibility.
# %sql SELECT name FROM sqlite_master WHERE type='table'

"""### Query the database system catalog to retrieve column metadata

#### Type in your query to retrieve the number of columns in the SCHOOLS table
"""

# Commented out IPython magic to ensure Python compatibility.
# %sql SELECT COUNT(name) FROM PRAGMA_TABLE_INFO('CHICAGO_PUBLIC_SCHOOLS');

"""#### Type in your query to retrieve all column names in the SCHOOLS table along with their datatypes and length

"""

# Commented out IPython magic to ensure Python compatibility.
# %sql SELECT name, type, LENGTH(type) FROM PRAGMA_TABLE_INFO('CHICAGO_PUBLIC_SCHOOLS');

"""### Questions
1. Is the column name for the "SCHOOL ID" attribute in upper or mixed case?

Mixed: "School_ID"

2. What is the name of "Community Area Name" column in your table? Does it have spaces?

COMMUNITY_AREA_NAME

3. Are there any columns in whose names the spaces and paranthesis (round brackets) have been replaced by the underscore character "_"?

Yes.

### Problem 1
How many Elementary Schools are in the dataset?
"""

# Commented out IPython magic to ensure Python compatibility.
# %%sql
# 
# SELECT COUNT(*) FROM CHICAGO_PUBLIC_SCHOOLS
# WHERE "Elementary, Middle, or High School" = 'ES';

"""### Problem 2
What is the highest Safety Score?
"""

# Commented out IPython magic to ensure Python compatibility.
# %%sql
# 
# SELECT MAX(SAFETY_SCORE) FROM CHICAGO_PUBLIC_SCHOOLS;

"""### Problem 3
Which schools have highest Safety Score?
"""

# Commented out IPython magic to ensure Python compatibility.
# %%sql
# 
# SELECT NAME_OF_SCHOOL FROM CHICAGO_PUBLIC_SCHOOLS
# WHERE SAFETY_SCORE = (SELECT MAX(SAFETY_SCORE) FROM CHICAGO_PUBLIC_SCHOOLS);

"""### Problem 4
What are the top 10 schools with the highest "Average Student Attendance"?
"""

# Commented out IPython magic to ensure Python compatibility.
# %%sql
# 
# SELECT NAME_OF_SCHOOL FROM CHICAGO_PUBLIC_SCHOOLS
# ORDER BY AVERAGE_STUDENT_ATTENDANCE DESC LIMIT 10;

"""### Problem 5
Retrieve the list of 5 Schools with the lowest Average Student Attendance sorted in ascending order based on attendance
"""

# Commented out IPython magic to ensure Python compatibility.
# %%sql
# 
# SELECT NAME_OF_SCHOOL, AVERAGE_STUDENT_ATTENDANCE FROM CHICAGO_PUBLIC_SCHOOLS
# WHERE AVERAGE_STUDENT_ATTENDANCE IS NOT NULL
# ORDER BY AVERAGE_STUDENT_ATTENDANCE LIMIT 5;

"""### Problem 6
Now remove the '%' sign from the above result set for Average Student Attendance column
"""

# Commented out IPython magic to ensure Python compatibility.
# %%sql
# 
# SELECT NAME_OF_SCHOOL, REPLACE(AVERAGE_STUDENT_ATTENDANCE, '%', '') FROM CHICAGO_PUBLIC_SCHOOLS
# WHERE AVERAGE_STUDENT_ATTENDANCE IS NOT NULL
# ORDER BY AVERAGE_STUDENT_ATTENDANCE LIMIT 5;

"""### Problem 7
Which Schools have Average Student Attendance lower than 70%?
"""

# Commented out IPython magic to ensure Python compatibility.
# %%sql
# 
# SELECT NAME_OF_SCHOOL, AVERAGE_STUDENT_ATTENDANCE FROM CHICAGO_PUBLIC_SCHOOLS
# WHERE AVERAGE_STUDENT_ATTENDANCE < 70;

"""### Problem 8
Get the total College Enrollment for each Community Area
"""

# Commented out IPython magic to ensure Python compatibility.
# %%sql
# 
# SELECT COMMUNITY_AREA_NAME, SUM(COLLEGE_ENROLLMENT) FROM CHICAGO_PUBLIC_SCHOOLS
# GROUP BY COMMUNITY_AREA_NAME;

"""### Problem 9
Get the 5 Community Areas with the least total College Enrollment sorted in ascending order
"""

# Commented out IPython magic to ensure Python compatibility.
# %%sql
# 
# SELECT COMMUNITY_AREA_NAME, SUM(COLLEGE_ENROLLMENT) FROM CHICAGO_PUBLIC_SCHOOLS
# GROUP BY COMMUNITY_AREA_NAME
# ORDER BY SUM(COLLEGE_ENROLLMENT) ASC LIMIT 5;

"""### Problem 10
List 5 schools with lowest safety score.
"""

# Commented out IPython magic to ensure Python compatibility.
# %%sql
# 
# SELECT NAME_OF_SCHOOL, SAFETY_SCORE FROM CHICAGO_PUBLIC_SCHOOLS
# WHERE SAFETY_SCORE IS NOT NULL
# ORDER BY SAFETY_SCORE ASC LIMIT 5;

"""### Problem 11
Get the hardship index for the community area of the school which has College Enrollment of 4368
"""

df = pd.read_csv("https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-DB0201EN-SkillsNetwork/labs/FinalModule_Coursera_V5/data/ChicagoCensusData.csv")
df.to_sql("CENSUS_DATA", con, if_exists='replace', index=False,method="multi")

# Commented out IPython magic to ensure Python compatibility.
# %%sql
# 
# SELECT Hardship_Index FROM CENSUS_DATA
# WHERE Community_Area_Number = (SELECT Community_Area_Number FROM CHICAGO_PUBLIC_SCHOOLS WHERE College_Enrollment = 4368);

"""### Problem 12
Get the hardship index for the community area which has the highest value for College Enrollment
"""

# Commented out IPython magic to ensure Python compatibility.
# %%sql
# 
# SELECT Hardship_Index FROM CENSUS_DATA
# WHERE Community_Area_Number = (SELECT Community_Area_Number FROM CHICAGO_PUBLIC_SCHOOLS WHERE College_Enrollment = (SELECT MAX(College_Enrollment) FROM CHICAGO_PUBLIC_SCHOOLS));