# -*- coding: utf-8 -*-
"""hands_on_lab_01.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OvCGEH85oX5n770eUYR4c0x-7Bi6QggI

## Hands-on Lab: Creating tables, inserting and querying Data
"""

# Install & load sqlite3

import sqlite3

# Connecting to sqlite
# connection object
conn = sqlite3.connect('INSTRUCTOR.db')

# cursor object
cursor_obj = conn.cursor()

"""### Create a table in the database"""

# Before creating a table, let's first check if the table already
# exists or not. To drop the table from a database, use the DROP
# query. A cursor is an object that helps execute the query and
# fetch the records from the database.

# Drop the table if already exists.
cursor_obj.execute("DROP TABLE IF EXISTS INSTRUCTOR")

# Creating table
table = """ create table IF NOT EXISTS INSTRUCTOR(ID INTEGER PRIMARY KEY NOT NULL, FNAME VARCHAR(20), LNAME VARCHAR(20), CITY VARCHAR(20), CCODE CHAR(2));"""

cursor_obj.execute(table)

print("Table is Ready")

"""### Insert data into the table"""

cursor_obj.execute('''insert into INSTRUCTOR values (1, 'Rav',
                  'Ahuja', 'TORONTO', 'CA')''')

cursor_obj.execute('''insert into INSTRUCTOR values
                    (2, 'Raul', 'Chong', 'Markham', 'CA'),
                    (3, 'Hima', 'Vasudevan', 'Chicago', 'US')''')

"""### Query data in the table"""

statement = '''SELECT * FROM INSTRUCTOR'''
cursor_obj.execute(statement)

print("All the data")

output_all = cursor_obj.fetchall()

for row_all in output_all:
  print(row_all)

## Fetch few rows from the table
statement = '''SELECT * FROM INSTRUCTOR'''
cursor_obj.execute(statement)

print("All the data")
# If you want to fetch few rows from the table we use fetchmany(numberofrows) and mention the number how many rows you want to fetch
output_many = cursor_obj.fetchmany(2)

for row_many in output_many:
  print(row_many)

# Fetch only FNAME from the table
statement = '''SELECT FNAME FROM INSTRUCTOR'''
cursor_obj.execute(statement)

print("All the data")

output_column = cursor_obj.fetchall()

for fetch in output_column:
  print(fetch)

query_update='''update INSTRUCTOR set CITY='MOOSETOWN'
                where FNAME="Rav"'''
cursor_obj.execute(query_update)

statement = '''SELECT * FROM INSTRUCTOR'''
cursor_obj.execute(statement)

print("All the data")

output1 = cursor_obj.fetchmany(2)

for row in output1:
  print(row)

"""### Retrieve data into Pandas"""

import pandas as pd

#retrieve the query results into a pandas dataframe
df = pd.read_sql_query("select * from instructor;", conn)

#print the dataframe
df

#print just the LNAME for first row in the pandas data frame
df.LNAME[0]

df.shape

"""### Close the Connection"""

# Close the connection
conn.close()